//
//  SSViewLicenseViewController.m
//  Spend Stack
//
//  Created by Jordan Morgan on 4/26/19.
//  Copyright © 2019 Jordan Morgan. All rights reserved.
//

#import "SSViewLicenseViewController.h"

@interface SSViewLicenseViewController ()

@property (nonatomic) License license;
@property (strong, nonatomic, nonnull) SSTextView *textview;

@end

@implementation SSViewLicenseViewController

#pragma mark - Initializer

- (instancetype)initWithLicense:(License)license
{
    self = [super init];
    
    if (self)
    {
        self.license = license;
        self.title = @"License";
        UIBarButtonItem *done = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(dismissController)];
        self.navigationItem.rightBarButtonItem = done;
        
        self.textview = [[SSTextView alloc] initWithTextStyle:UIFontTextStyleCaption1];
        self.textview.frame = self.view.bounds;
        self.textview.editable = NO;
        self.textview.scrollEnabled = YES;
        self.textview.dataDetectorTypes = UIDataDetectorTypeLink;
        [self.view addSubview:self.textview];
        [self.textview mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.view.mas_safeAreaLayoutGuideTop).with.offset(SSTopElementMargin);
            make.left.equalTo(self.view.mas_leftMargin);
            make.right.equalTo(self.view.mas_rightMargin);
            make.bottom.equalTo(self.view.mas_safeAreaLayoutGuideBottom).with.offset(SSBottomBigElementMargin);
        }];
        
        self.view.backgroundColor = [UIColor systemBackgroundColor];
    }
    
    return self;
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    self.textview.text = [self markDownTextForLicense:self.license];
}

#pragma mark - Lazy Text Generation

- (NSString *)markDownTextForLicense:(License)license
{
    switch (license)
    {
        case LicenseFMDB:
            return [self fmdbText];
            break;
        case LicenseMasonry:
            return [self masonryText];
            break;
        case LicenseIGListKit:
            return [self igListKitText];
            break;
        default:
            return @"";
            break;
    }
}

- (NSString *)masonryText
{
    return @"Copyright (c) 2011-2012 Masonry Team - https://github.com/Masonry \n\n"
    "Permission is hereby granted, free of charge, to any person obtaining a copy "
    "of this software and associated documentation files (the \"Software\"), to deal"
    "in the Software without restriction, including without limitation the rights"
    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"
    "copies of the Software, and to permit persons to whom the Software is"
    "furnished to do so, subject to the following conditions:\n\n"
    "The above copyright notice and this permission notice shall be included in"
    "all copies or substantial portions of the Software.\n\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN "
    "THE SOFTWARE.\n\n"
    "Generated by CocoaPods - https://cocoapods.org";
}

- (NSString *)fmdbText
{
    return @"If you are using FMDB in your project, I'd love to hear about it. Let Gus know"
    "by sending an email to gus@flyingmeat.com.\n\n"
    "And if you happen to come across either Gus Mueller or Rob Ryan in a bar, you "
    "might consider purchasing a drink of their choosing if FMDB has been useful to"
    "you.\n\n"
    "Finally, and shortly, this is the MIT License.\n\n"
    "Copyright (c) 2008-2014 Flying Meat Inc.\n\n"
    "Permission is hereby granted, free of charge, to any person obtaining a copy"
    "of this software and associated documentation files (the \"Software\"), to deal"
    "in the Software without restriction, including without limitation the rights"
    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"
    "copies of the Software, and to permit persons to whom the Software is"
    "furnished to do so, subject to the following conditions:\n\n"
    "The above copyright notice and this permission notice shall be included in"
    "all copies or substantial portions of the Software.\n\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN"
    "THE SOFTWARE.";
}

- (NSString *)igListKitText
{
    return @"MIT License\n\n"
    "Copyright (c) 2016-present, Facebook, Inc.\n\n"
    "Permission is hereby granted, free of charge, to any person obtaining a copy"
    "of this software and associated documentation files (the \"Software\"), to deal"
    "in the Software without restriction, including without limitation the rights"
    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"
    "copies of the Software, and to permit persons to whom the Software is"
    "furnished to do so, subject to the following conditions:\n\n"
    "The above copyright notice and this permission notice shall be included in all"
    "copies or substantial portions of the Software.\n\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"
    "SOFTWARE.";
}

@end
